# This rule is not used by the project base-project itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the webapp.webapp.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: base-project
    app.kubernetes.io/managed-by: kustomize
  name: eg1-editor-role
rules:
- apiGroups:
  - webapp.webapp.example.com
  resources:
  - eg1s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.webapp.example.com
  resources:
  - eg1s/status
  verbs:
  - get
