name: Kubebuilder Auto Update POC

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" 

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install Latest Kubebuilder CLI
        run: |
          curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/latest/download/kubebuilder_linux_amd64 \
          -o kubebuilder && chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/kubebuilder

      - name: Run Kubebuilder Alpha Generate
        run: |
          kubebuilder alpha generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto-update: Re-scaffolded using Kubebuilder alpha generate"
          title: "Auto Update: Re-scaffolded Kubebuilder Project"
          body: |
            This PR was created automatically to apply scaffold updates via `kubebuilder alpha generate`.
          branch: kubebuilder-auto-update
