name: Kubebuilder Auto Update POC

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight UTC

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Install Kubebuilder
        run: |
          curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v4.1.0/kubebuilder_linux_amd64 -o kubebuilder
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/kubebuilder

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Kubebuilder Alpha Generate
        run: |
          kubebuilder alpha generate

      - name: Commit Changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-update: Re-scaffolded using Kubebuilder alpha generate"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto-update: Re-scaffolded using Kubebuilder alpha generate"
          title: "Auto Update: Re-scaffolded Kubebuilder Project"
          body: |
            This PR was created automatically to apply scaffold updates via `kubebuilder alpha generate`.
          branch: kubebuilder-auto-update
